# Set update schedule for GitHub Actions

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      # check at 3am UTC
      time: "03:00"
    open-pull-requests-limit: 20

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: daily
      # check at 3am UTC
      time: "03:00"
    open-pull-requests-limit: 20
    groups:
      argosci:
        applies-to: version-updates
        patterns:
          - "@argos-ci/*"
      storybook:
        applies-to: version-updates
        patterns:
          - "@storybook/*"
          - "storybook"
          - "storybook-dark-mode"
      commitlint:
        applies-to: version-updates
        patterns:
          - "@commitlint/*"
      docusaurus:
        applies-to: version-updates
        patterns:
          - "@docusaurus/*"
      eslint:
        applies-to: version-updates
        patterns:
          - "eslint"
          - "@eslint/*"
      fortawesome:
        applies-to: version-updates
        patterns:
          - "@fortawesome/*"
      typescript-eslint:
        applies-to: version-updates
        patterns:
          - "@typescript-eslint/*"
          - "typescript-eslint"
      tailwindcss:
        applies-to: version-updates
        patterns:
          - "@tailwindcss/*"
          - "tailwindcss"
      vitest:
        applies-to: version-updates
        patterns:
          - "@vitest/*"
          - "vitest"
      typedoc:
        applies-to: version-updates
        patterns:
          - "typedoc"
          - "typedoc-plugin-markdown"
          - "docusaurus-plugin-typedoc"


  - package-ecosystem: npm
    directory: /extensions/compose
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /extensions/docker
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /extensions/kind
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /extensions/kube-context
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /extensions/kubectl-cli
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /extensions/lima
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /extensions/podman/packages/api
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /extensions/podman/packages/extension
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /extensions/registries
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/extension-api
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/preload-webview
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/renderer
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/ui
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/webview-api
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /storybook
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /tests/playwright
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /tools
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /website-argos
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /website
    schedule:
      interval: daily
